In [75]:
import numpy as np


In [3]:
x = np.arange(1,13).reshape((6,2))
print(x)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [9]:
x = np.arange(10,37, dtype = np.float64). reshape((3,3,3))
x

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [81]:
a =np.arange(1,100*10+1).reshape((100,10))
x = a [(a % 7 == 0) & (a % 5 ==0)]
print(x)

[ 35  70 105 140 175 210 245 280 315 350 385 420 455 490 525 560 595 630
 665 700 735 770 805 840 875 910 945 980]


In [41]:
print("original matrix")
arr = np.arange(9).reshape(3,3)
print(arr)
print("swaped matrix")
arr[:,[0,1]] = arr[:,[1,0]]
arr

original matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
swaped matrix


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [44]:
z= np.zeros((4,5), dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [82]:
arr = np.zeros(10, dtype=int)
print(arr)
print("\n Update fifth and eighth value")
arr[4] = 10
arr[7] = 20
print(arr)

[0 0 0 0 0 0 0 0 0 0]

 Update fifth and eighth value
[ 0  0  0  0 10  0  0 20  0  0]


In [46]:
x = np.zeros(4, dtype=np.int64)
x

array([0, 0, 0, 0], dtype=int64)

In [58]:
x = np.full((2, 5), 6, dtype=np.uint32)
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [60]:
a=np.arange(2,101,2)
print("\nArray of all the even integers from 2 to 100")
a


Array of all the even integers from 2 to 100


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [85]:
arr = np.array([[3,3,3,],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
sub = arr[0]-brr[0],  arr[1]-brr[1], arr[2]-brr[2]
sub

(array([2, 2, 2]), array([2, 2, 2]), array([2, 2, 2]))

In [2]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])  
arr[arr%2==1] = -1  
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr = np.array([1,2,3])
arr1 = np.repeat(arr,3)
ans = np.hstack((arr1,arr,arr,arr))
ans

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
a = np.array([2,6,1,9,10,3,27])
print("Original array:")
print(a)
ind_pos = np.where(np.logical_and(a>5, a<10))
print("values in a range 5 to 10:")
arr[ind_pos]

Original array:
[ 2  6  1  9 10  3 27]
values in a range 5 to 10:


array([6, 9])

In [51]:
print("Creating 8X3 array using numpy.arange")
arr = np.arange(10,34,1)
arr = arr.reshape(8,3)
print (arr)

print("Dividing 8X3 array into 4 sub array\n")
ans = np.split(sampleArray, 4) 
print(ans)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [66]:
arr = np.array([[8,2,-2],[-4,1,7],[6,3,9]])
arr
ans = arr[np.argsort(arr[:,1])]
ans

array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [82]:
x = np.array([[1],[2],[3]])
y = np.array([[2],[3],[4]])
ans = np.dstack((x, y))
print (ans)

[[[1 2]]

 [[2 3]]

 [[3 4]]]


In [111]:
arr = np.arange(1,10*10+1).reshape(10,10)
arr




array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])