In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np


In [4]:
x=[1,2,3,4,5,6]
nums = np.array([1,2,3,4,5,6])
type(nums)

numpy.ndarray

In [18]:
#1D array
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#2D array
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
#3d array
c= np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
# multidimension
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [22]:
#minimum dimension
e = np.array([0,1,2,3,4,5,6], ndmin=2)
e

array([[0, 1, 2, 3, 4, 5, 6]])

In [23]:
#dtype perameters
f = np.array([1,2,3,4,5], dtype = complex)
f

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [25]:
#ndim
a = np.array([(1,2,3),(4,5,6)])
a.ndim

2

In [27]:
#itemsize
b = np.array([(1,2,3)])
b.itemsize

8

In [28]:
#dtype
a.dtype

dtype('int64')

In [29]:
#size
a.size

6

In [30]:
#shape
a.shape

(2, 3)

In [38]:
#slicing
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a[0:,1])

[2 6]


In [43]:
#boolean 
bool_arr = np.array([1, .5, 0, 'aa', ''], dtype = bool)
print(bool_arr)

[ True  True False  True False]


In [44]:
#multidim
a= np.array([(2,3),(4,5),(7,8)])
a[0:2,1]

array([3, 5])

In [46]:
#linearly spacing
a = np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [51]:
#minimum valus
a = np.array([1,2,3])
a.min()

1

In [50]:
#maximum valus
a.max()

3

In [54]:
#get a sum
a = np.array([1,2,3])
a.sum()

6

In [55]:
# get square root
np.sqrt(a)


array([1.        , 1.41421356, 1.73205081])

In [57]:
#subtracting metrix
x= np.array([(1,2,3),(3,4,5)])
y = np.array([(5,6,7),(6,7,8)])
x-y

array([[-4, -4, -4],
       [-3, -3, -3]])

In [58]:
#Adding Matrix
x+y

array([[ 6,  8, 10],
       [ 9, 11, 13]])

In [59]:
#multiply matrix
x*y

array([[ 5, 12, 21],
       [18, 28, 40]])

In [60]:
#Divide matrix
x/y

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.57142857, 0.625     ]])

In [63]:
#vertical Stack
np.vstack((x,y))

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

In [64]:
#horizantal stack
np.hstack((x,y))

array([[1, 2, 3, 5, 6, 7],
       [3, 4, 5, 6, 7, 8]])

In [65]:
#contiguous flattened array
x.ravel()

array([1, 2, 3, 3, 4, 5])

In [67]:
#odd number filtering
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1 ]

array([1, 3, 5, 7, 9])

In [70]:
#zero Array
arrayid = np.zeros(3)
arrayid

array([0., 0., 0.])

In [74]:
#2D zero matrix
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
#logspace array
A = np.logspace(3,8,num=10,base= 1000.0, dtype=float)
A


array([1.00000000e+09, 4.64158883e+10, 2.15443469e+12, 1.00000000e+14,
       4.64158883e+15, 2.15443469e+17, 1.00000000e+19, 4.64158883e+20,
       2.15443469e+22, 1.00000000e+24])

In [77]:
#generate random number
np.random.rand(3,3)

array([[0.41817801, 0.43504858, 0.28652718],
       [0.09347413, 0.18384812, 0.40748794],
       [0.61559137, 0.00906787, 0.10262126]])

In [83]:
#random number in a given range
np.random.randint(2, size= 5)


array([1, 1, 1, 0, 0])

In [84]:
np.random.randint(15, size= (2,3))

array([[ 5,  3, 13],
       [11,  3,  7]])

In [85]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
#digonal array
np.diag(np.arange(0,8,1))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

In [98]:
np.diag(np.diag(np.arange(12).reshape((4,3))))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [99]:
#numpy indexing
a1 = np.array([1,2,3,4,5,6])
a1[[0,1]]

array([1, 2])

In [101]:
#last value
a1[-1]

6

In [104]:
#joining and stacking Araays
Arr1= np.array([[1,2,3],[4,5,6]])
Arr2 = np.array([[6,7,8],[7,8,9]])
Arr1+Arr2

array([[ 7,  9, 11],
       [11, 13, 15]])

In [106]:
np.hstack((Arr1,Arr2))

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [107]:
np.vstack((Arr1,Arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8],
       [7, 8, 9]])

In [109]:
#concatinating
np.concatenate((Arr1, Arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8],
       [7, 8, 9]])

In [113]:
#append value
np.append(Arr1,Arr2, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8],
       [7, 8, 9]])

In [115]:
np.append(Arr1,Arr2, axis= 1)

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [116]:
#trignomatry
np.sin(Arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [117]:
np.cos(Arr2)

array([[ 0.96017029,  0.75390225, -0.14550003],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [119]:
np.tan(Arr1)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [120]:
np.log(Arr2)

array([[1.79175947, 1.94591015, 2.07944154],
       [1.94591015, 2.07944154, 2.19722458]])

In [121]:
np.exp(Arr1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [122]:
np.sqrt(Arr2)

array([[2.44948974, 2.64575131, 2.82842712],
       [2.64575131, 2.82842712, 3.        ]])

In [125]:
np.power(Arr1, 5)

array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [126]:
np.ceil(Arr2)

array([[6., 7., 8.],
       [7., 8., 9.]])

In [127]:
np.sign(Arr1)

array([[1, 1, 1],
       [1, 1, 1]])

In [130]:
np.reciprocal(Arr1)

array([[1, 0, 0],
       [0, 0, 0]])

In [131]:
np.remainder((Arr2),3)

array([[0, 1, 2],
       [1, 2, 0]])

In [134]:
np.round(Arr2)

array([[6, 7, 8],
       [7, 8, 9]])